version: '3.8'

services:
  lifx-soundboard:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - audio_files:/app/audio-files
    networks:
      - lifx-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  audio_files:
    driver: local

networks:
  lifx-network:
    driver: bridge